feat(grid): #RDV-22 creation of a grid (sql + api route)
OPEN-ENT-NG/appointments pull request #1
Opened 2024-10-15 11:43 UTC by niko-amosse

## Description

This PR marks the initialization of the repository and establishes the necessary architecture for creating a grid. The following changes have been made:

- **Repository Initialization**: Created the repository with the basic file structure for the project.
- **SQL Scripts**: Added SQL scripts for creating the necessary tables for grid management. This includes tables for `DailySlots` and other relevant entities.
- **API Routes**: Set up API routes to enable the creation, updating, and retrieval of grids. This will facilitate interaction with grid data through HTTP requests.
- **Data Validation**: Implemented data validation to ensure that the created grids comply with defined business rules.
- **Error Handling**: Added error handling to manage insertion failures and ensure appropriate responses in case of issues.

## Issue ticket number and link

[RDV-22](https://jira.support-ent.fr/browse/RDV-22)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)
- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-10-16 07:35 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/helper/FutureHelper.java
copié collé de form

2024-10-16 07:35 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/helper/IModelHelper.java
copié collé de form

2024-10-16 07:37 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/model/IModel.java
copié collé de form

2024-10-16 07:37 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/model/TransactionElement.java
copié collé de form

2024-10-16 08:04 UTC, Rseuret commented
Manque les TUs pour l'api création à minima

2024-10-16 08:05 UTC, Rseuret approved these changes

2024-10-17 14:08 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/core/constants/Fields.java
NE PAS LIRE : PAS DE MODIF

2024-10-17 14:08 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/core/constants/SqlTables.java
NE PAS LIRE : PAS DE MODIF

2024-10-18 08:01 UTC, JinDouang commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultGridRepository.java
> +    private Future<JsonArray> checkIfGridExists(String gridName, String userId) {
ce genre de fonction doit plutôt aller dans  un service

vu ta query sql, ca pourrait être + global

2024-10-18 08:01 UTC, JinDouang commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultGridRepository.java
> +        return checkIfGridExists(grid.getGridName(), userId)
tu es obligé de le vérifier en java ?

2024-10-18 08:02 UTC, JinDouang commented on backend/src/main/java/fr/openent/appointments/service/Impl/DefaultGridService.java
> +                return gridRepository.create(grid, user.getUserId());
tu peux le faire en une ligne (lambda)

2024-10-22 16:33 UTC, JinDouang requested changes

2024-10-22 16:33 UTC, JinDouang commented on backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java
> +                        log.error("[CommunicationController@getVisibleGroups] Failed to retrieve visible groups", error.getMessage());
pas le bon format, tu ne log pas la stack trace

2024-10-22 16:33 UTC, JinDouang commented on backend/src/main/java/fr/openent/appointments/controller/GridController.java
> +                    log.error("[Appointments@GridController:createGrid] Failed to create grid", error.getMessage());
pas le bon format log

2024-10-22 16:33 UTC, JinDouang commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultGridRepository.java
> +            queryBuilder.append(" AND ").append(Fields.STATE).append(" IN (");
Tu peux utiliser Sql.listPrepared

exemple usage : https://github.com/OPEN-ENT-NG/presences/blob/dev/presences/src/main/java/fr/openent/presences/service/impl/DefaultEventService.java#L187

2024-10-22 16:33 UTC, JinDouang commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultGridRepository.java
> +            for (int i = 0; i < gridStates.size(); i++) {
idem

2024-10-23 12:53 UTC, qperie requested changes

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java
> +        UserUtils.getUserInfos(eb, request, user -> {
utilise la version Future, tu pourras tout chainer comme ça

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java
> +                        String errorMessage = "Appointments@CommunicationController::getVisibleGroups" + error.getMessage();
Manque les crochets pour l'en-tête et un espace à la fin sinon tout ton texte va être collé là.
Et je te conseille d'utiliser le String.format() pour minimiser les risques d'erreurs sur les noms de class en général (même si ici c'est ok)

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java
> +                renderError(request);
Tout retour d'erreur devrait avoir son log.error() avec

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/controller/GridController.java
> +                    String errorMessage = "[Appointments@GridController::createGrid] Failed to create grid" + error.getMessage();
```suggestion
                    String errorMessage = "[Appointments@GridController::createGrid] Failed to create grid " + error.getMessage();

```

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/controller/MainController.java
> +    }
Si tu veux être 100% cohérent tu peux faire pareil pour le VIEW_RIGHT

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/model/payload/GridPayload.java
> +        this.publicComment = grid.getString(Fields.CAMEL_PUBLIC_COMMENT, "");
C'est bien de prendre l'habitude de mettre des valeurs par défaut 👍

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultCommunicationRepository.java
> +		JsonObject params = new JsonObject().put("userId", userId);
indentation

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultGridRepository.java
> +                        Long gridId = insertedGridId.getLong("id");
Magic string et default value

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultGridRepository.java
> +                            .map(inserted -> new JsonObject().put("gridId", gridId));
Magic string

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/service/Impl/DefaultCommunicationService.java
> +            .onFailure(err -> promise.fail(err));
log.error()

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/service/Impl/DefaultGridService.java
> +            .onFailure(err -> promise.fail(err));
log.error()

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/service/Impl/DefaultGridService.java
> +            .onFailure(promise::fail);
log.error()

2024-10-23 12:53 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/service/Impl/DefaultGridService.java
> +            .onSuccess(gridId -> promise.complete(new JsonObject().put("gridId", gridId)))
Magic string

2024-10-23 12:53 UTC, qperie commented on build.sh
> +main "$@"
Tu pourras ajouter des params stp ?
Qu'on puisse call ces functions via des "./build.sh frontEnd", "./build.sh backEnd", "./build.sh install", "./build.sh testFront", ...

2024-10-24 08:32 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java
> +        UserUtils.getUserInfos(eb, request, user -> {
fait

2024-10-24 08:32 UTC, niko-amosse commented on backend/src/main/java/fr/openent/appointments/controller/CommunicationController.java
> +                renderError(request);
fait

2024-10-24 12:34 UTC, qperie approved these changes

2024-10-24 12:34 UTC, qperie commented on backend/src/main/java/fr/openent/appointments/repository/Impl/DefaultCommunicationRepository.java
> +		JsonObject params = new JsonObject().put("userId", userId);
J'avais pas vu mais magic string (+ toujours l'indentation de cette ligne)

2024-10-24 12:34 UTC, qperie commented on build.sh
> +main "$@"
En vrai ça marche comme approche mais t'étais pas obligé de t'embêter, t'avais plein d'exemples avec les autres modules  (ex : https://github.com/OPEN-ENT-NG/form/blob/dev/build.sh#L134 ou https://github.com/OPEN-ENT-NG/magneto/blob/dev/build.sh#L92)

2024-10-25 08:44 UTC, merged